server {
    listen 8080;
    listen [::]:8080;
    server_name localhost;
    charset utf-8;
    sendfile on;
    server_tokens off;
    more_clear_headers Server;

    # Buffers
    client_body_buffer_size 16k;
    client_max_body_size 2m;
    client_body_in_single_buffer on;
    client_header_buffer_size 1m;
    large_client_header_buffers 4 8k;

    # Security headers
    set $CSP_DEFAULT "default-src 'self'";
    set $CSP_SCRIPT "script-src 'self'";
    set $CSP_SCRIPT "${CSP_SCRIPT} 'nonce-$request_id'";
    set $CSP_IMG "img-src 'self'";
    set $CSP_CONNECT "connect-src 'self'";
    set $CSP_FONT "font-src 'self'";
    set $CSP_STYLE "style-src 'self'";
    set $CSP_STYLE "${CSP_STYLE} 'nonce-$request_id'";
    set $CSP_FRAME "frame-src 'self'";
    set $CSP_FRAME_ANCESTORS "frame-ancestors 'self'";

    add_header Content-Security-Policy "${CSP_SCRIPT}; ${CSP_DEFAULT}; ${CSP_STYLE}; ${CSP_CONNECT}; ${CSP_IMG}; ${CSP_FONT}; ${CSP_FRAME}; ${CSP_FRAME_ANCESTORS};" always;
    add_header Cache-Control "must-revalidate" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header X-XSS-Protection "1; mode=block" always;

    sub_filter_once off;
    sub_filter noncePlaceholder $request_id;

    # Root
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
        limit_except GET HEAD { deny all; }
        autoindex off;
        expires 10m;
    }

    error_page 404 /404.html;
    error_page 400 401 402 403 500 501 502 503 504 505 507 /50x.html;
}
